### PR TITLE
Added a PyLint check via Travis CI.

### PR DESCRIPTION
**Pull request by JeremyRand**

### CODE REVIEW

**Comment by phelixbtc** [comment]
Can't test. Somebody else?

**Comment by JeremyRand** [comment]
You can see the result of the Travis CI run at https://travis-ci.org/JeremyRand/nmcontrol/builds/62530054

**Comment by phelixbtc** [comment]
Untested ACK

**Comment by JeremyRand** [comment]
Merging since this doesn't affect any existing code, and Phelix seems okay with it.

**Pull request merged**
